### ISSUE TITLE
Problemi con il form

### ISSUE THREAD

**Issue by ntnpgls** [ondata/rastrellierebologna#10]
Ciao,

io con iOS ho dei problemi con il form, questo l'errore: IDBFactory.open() called in an invalid security context

<img width="544" alt="screen shot 2018-02-06 at 12 23 41" src="https://user-images.githubusercontent.com/36171957/35857507-ab01d7f2-0b39-11e8-8c79-f84736c8f771.png">

**Comment by lorenzoperone** [comment]
ciao @ntnpgls (Antonio :) puoi provare ad inserire una rastrelliera con il form "nudo" a [questo](https://ona.io/lorenzo_perone/50895/271675/webform) indirizzo?
Grazie.

**Comment by ntnpgls** [comment]
Il form "nudo" va alla grande! :)

**Comment by lorenzoperone** [comment]
Ottimo,
credo che il tuo browser sia "prudente" e non apprezzi il fatto che richiamiamo delle pagine esterne, in questo caso basta allora aprire nel browser diverse finestre da questi indirizzi:

* [Mappa](http://umap.openstreetmap.fr/it/map/mappiamobo_194853#13/44.5041/11.3417)
* [Form](https://enketo.ona.io/x/#YJWZ)
* [Dashboard](https://ona.io/lorenzo_perone/50895/271675#/saved-charts)
* [Help](https://ondata.github.io/rastrellierebologna/help_mappiamobo.html)
