### ISSUE TITLE
Modifica attributi rastrelliera

### ISSUE THREAD

**Issue by cipins** [ondata/rastrellierebologna#13]
Sarebbe utile una funzione di modifica degli attributi di una rastrelliera esistente, a partire dalla selezione in mappa

**Comment by lorenzoperone** [comment]
E' possibile attraverso il backend di ONA, si possono modificare tutti gli attributi e la posizione

**Comment by lorenzoperone** [comment]
I dati sono potenzialmente editabili anche da UMAP, è necessario però creare un layer statico indipendente da quello dinamico collegato al Google Sheet
